name: CI - Build & Test with GitHub Runner

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Copy .env
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Generate application key
        run: php artisan key:generate

      - name: Set folder permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run tests
        run: php artisan test
