name: Deploy via Self-Hosted Runner

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout kode terbaru
        uses: actions/checkout@v4

      - name: Sync ke folder serving via rsync
        run: |
          rsync -av --delete \
            --exclude='.env' \
            --exclude='.git' \
            ./ /var/www/devops-demo/

      - name: Install dependencies
        run: |
          cd /var/www/devops-demo
          composer install --no-dev --optimize-autoloader
      - name: Run database migrations
        run: |
          cd /var/www/devops-demo
          php artisan migrate --force
